// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagment.DataLayer.Context;

namespace VisitorManagment.DataLayer.Migrations
{
    [DbContext(typeof(VisitorManagmentContext))]
    [Migration("20221101063956_mig_adddepartment_table1")]
    partial class mig_adddepartment_table1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Permissions.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IconName")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("ParentUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PermissionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ShowAll")
                        .HasColumnType("bit");

                    b.Property<string>("SubUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PermissionId");

                    b.HasIndex("ParentID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Permissions.RolePermission", b =>
                {
                    b.Property<int>("RP_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RP_Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.EshrafPeriodDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EshrafPeriodDefs");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodeGha")
                        .HasColumnType("int");

                    b.Property<int>("EshrafPeriodDefId")
                        .HasColumnType("int");

                    b.Property<int?>("FinalPoint")
                        .HasColumnType("int");

                    b.Property<string>("GhaTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PointEghdam")
                        .HasColumnType("int");

                    b.Property<int?>("PointNezaja")
                        .HasColumnType("int");

                    b.Property<int?>("PointReject")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("UnitCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EshrafPeriodDefId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.TblDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentCode")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentFatherCode")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DepartmentTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DepartmentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMostaghel")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("TblDepartmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UnitCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblDepartmentTypeId");

                    b.ToTable("TblDepartments");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.TblDepartmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblDepartmentTypes");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.ZaribRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Zarib")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ZaribRankings");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int?>("SortNum")
                        .HasColumnType("int");

                    b.Property<int?>("SortNumMoavenat")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.UserRole", b =>
                {
                    b.Property<int>("UR_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserSubId")
                        .HasColumnType("int");

                    b.HasKey("UR_Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.UserSub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodGha")
                        .HasColumnType("int");

                    b.Property<string>("CodGhaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FPrsnNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobDes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UnitCode")
                        .HasColumnType("int");

                    b.Property<int?>("UnitDutyCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitDutyTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("UserSub");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CodGha")
                        .HasColumnType("int");

                    b.Property<string>("CodGhaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EditUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("JobDes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RankCode")
                        .HasColumnType("int");

                    b.Property<string>("RankTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int>("UnitCode")
                        .HasColumnType("int");

                    b.Property<int?>("UnitDutyCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitDutyTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserAvatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Views.ViwFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachDastor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodGha")
                        .HasColumnType("int");

                    b.Property<string>("CodGhaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountVam")
                        .HasColumnType("int");

                    b.Property<float>("DRSAD_JA")
                        .HasColumnType("real");

                    b.Property<float>("DRSAD_JB")
                        .HasColumnType("real");

                    b.Property<int>("EditUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EzamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmandehPersonalCode")
                        .HasColumnType("int");

                    b.Property<string>("FarmandehPersonalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FishAttachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMeetingHold")
                        .HasColumnType("bit");

                    b.Property<int>("IsarStatus")
                        .HasColumnType("int");

                    b.Property<string>("JobDes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int>("MelliCode")
                        .HasColumnType("int");

                    b.Property<int>("PersonalCode")
                        .HasColumnType("int");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankCode")
                        .HasColumnType("int");

                    b.Property<string>("RankTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ReciveMoney")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<string>("RequestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("RequestSubjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusTitle")
                        .HasColumnType("int");

                    b.Property<long>("SumAghsatVamMahiyaneh")
                        .HasColumnType("bigint");

                    b.Property<int>("TCount")
                        .HasColumnType("int");

                    b.Property<int>("TOT_AML")
                        .HasColumnType("int");

                    b.Property<int>("TOT_AML2")
                        .HasColumnType("int");

                    b.Property<long>("TotalMoney")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitCode")
                        .HasColumnType("int");

                    b.Property<int>("UnitDutyCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitDutyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceRecord")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViwFiles");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Views.ViwHamesh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ActionTypeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodGha")
                        .HasColumnType("int");

                    b.Property<string>("CodGhaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("RequestSubjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RoleTypeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TCount")
                        .HasColumnType("int");

                    b.Property<int>("UnitCode")
                        .HasColumnType("int");

                    b.Property<int>("UnitDutyCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitDutyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserSubId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ViwHamesh");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.AvamerSadereh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AvamerSaderehs");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.BoseMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RankTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BoseMeetings");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Cartable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.Property<int>("RcvrUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SndrUserId")
                        .HasColumnType("int");

                    b.Property<int>("StateCd")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Cartables");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.ClerkMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RankTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ClerkMeetings");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.FileAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("FileUplodeAttacmentDastor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.FileStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FileStatuses");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AttachDastor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Attachment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CodGha")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("CodGhaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CountVam")
                        .HasColumnType("int");

                    b.Property<decimal?>("DRSAD_JA")
                        .HasMaxLength(200)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DRSAD_JB")
                        .HasMaxLength(200)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EditDate")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<int?>("EditUserId")
                        .HasColumnType("int");

                    b.Property<string>("EmploymentDate")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EzamDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FarmandehPersonalCode")
                        .HasColumnType("int");

                    b.Property<string>("FarmandehPersonalName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FileStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FishAttachment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMeetingHold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMoavenatAnswered")
                        .HasColumnType("bit");

                    b.Property<string>("IsarStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobDes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("MablaghVamMohaghaghSode")
                        .HasColumnType("bigint");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("MelliCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RankCode")
                        .HasColumnType("int");

                    b.Property<string>("RankTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ReciveMoney")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegDate")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("StatusTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("SumAghsatVamMahiyaneh")
                        .HasColumnType("bigint");

                    b.Property<long?>("SumMablaghVamDarkhasti")
                        .HasColumnType("bigint");

                    b.Property<string>("TOT_AML")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TOT_AML2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TotalMoney")
                        .HasColumnType("bigint");

                    b.Property<int?>("UnitCode")
                        .HasColumnType("int");

                    b.Property<int?>("UnitDutyCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitDutyTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VoiceRecord")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FileStatusId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequestSubjectId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Hamesh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<long?>("MablaghVamDarkhasti")
                        .HasColumnType("bigint");

                    b.Property<long?>("MablaghVamMohaghaghSode")
                        .HasColumnType("bigint");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RoleTypeTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserSubId")
                        .HasColumnType("int");

                    b.Property<int?>("VamCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("FileId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubId");

                    b.HasIndex("VamCodeId");

                    b.ToTable("Hameshes");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoseMeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ClerkMeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EditUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOkay")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IsOkayDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsOkayRegUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingPlaceId")
                        .HasColumnType("int");

                    b.Property<int>("MeetingStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("StartMeetingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("regUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoseMeetingId");

                    b.HasIndex("ClerkMeetingId");

                    b.HasIndex("MeetingPlaceId");

                    b.HasIndex("MeetingStatusId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.MeetingPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MeetingPlaces");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.MeetingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MeetingStaus");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BirthDate")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BirthPlaceTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BloodTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CodGha")
                        .HasColumnType("int");

                    b.Property<string>("CodGhaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DRSAD_JA")
                        .HasMaxLength(200)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DRSAD_JB")
                        .HasMaxLength(200)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EditDate")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<int?>("EditUserId")
                        .HasColumnType("int");

                    b.Property<string>("EmploymentDate")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmploymentTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EzamDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FarmandehPersonalCode")
                        .HasColumnType("int");

                    b.Property<string>("FarmandehPersonalName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IsarStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JobDes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MarridTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MelliCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalAvatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PersonalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RankCode")
                        .HasColumnType("int");

                    b.Property<string>("RankTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegDate")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReligoinTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StatusTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TOT_AML")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TOT_AML2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UnitCode")
                        .HasColumnType("int");

                    b.Property<int?>("UnitDutyCode")
                        .HasColumnType("int");

                    b.Property<string>("UnitDutyTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Personals");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.RequestSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RequestSubjects");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.SMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortNumber")
                        .HasColumnType("int");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleFa")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("SMS");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Vam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodeVam")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VamCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("VamCodeId");

                    b.ToTable("Vams");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.VamCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("SortNum")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VamCodes");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.WorkFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EditUserId")
                        .HasColumnType("int");

                    b.Property<int>("RcvrRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int>("SndrRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("RcvrRoleId");

                    b.ToTable("WorkFlows");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Permissions.Permission", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.Permissions.Permission", null)
                        .WithMany("Permissions")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Permissions.RolePermission", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.Permissions.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.User.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.Point", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.Ranking.EshrafPeriodDef", "EshrafPeriodDef")
                        .WithMany("Points")
                        .HasForeignKey("EshrafPeriodDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EshrafPeriodDef");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.TblDepartment", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.Ranking.TblDepartmentType", "TblDepartmentType")
                        .WithMany("TblDepartments")
                        .HasForeignKey("TblDepartmentTypeId");

                    b.Navigation("TblDepartmentType");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.UserRole", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.User.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.User.Users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.User.UserSub", "UserSub")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserSubId");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("UserSub");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Cartable", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", "File")
                        .WithMany("Cartables")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.FileAttachment", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", "File")
                        .WithMany("FileAttachments")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.FileStatus", "FileStatus")
                        .WithMany("Files")
                        .HasForeignKey("FileStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Meeting", "Meeting")
                        .WithMany("Files")
                        .HasForeignKey("MeetingId");

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Personal", "Personal")
                        .WithMany("Files")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Priority", "Priority")
                        .WithMany("Files")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.RequestSubject", "RequestSubject")
                        .WithMany("Documents")
                        .HasForeignKey("RequestSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileStatus");

                    b.Navigation("Meeting");

                    b.Navigation("Personal");

                    b.Navigation("Priority");

                    b.Navigation("RequestSubject");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Hamesh", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.ActionType", "ActionType")
                        .WithMany("Hameshes")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", "File")
                        .WithMany("Hameshes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Hamesh", null)
                        .WithMany("Hameshes")
                        .HasForeignKey("ParentId");

                    b.HasOne("VisitorManagment.DataLayer.Entities.User.Users", "User")
                        .WithMany("Hameshes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.User.UserSub", "UserSub")
                        .WithMany("Hameshes")
                        .HasForeignKey("UserSubId");

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.VamCode", null)
                        .WithMany("Hameshes")
                        .HasForeignKey("VamCodeId");

                    b.Navigation("ActionType");

                    b.Navigation("File");

                    b.Navigation("User");

                    b.Navigation("UserSub");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Meeting", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.BoseMeeting", "BoseMeeting")
                        .WithMany()
                        .HasForeignKey("BoseMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.ClerkMeeting", "ClerkMeeting")
                        .WithMany()
                        .HasForeignKey("ClerkMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.MeetingPlace", "MeetingPlace")
                        .WithMany()
                        .HasForeignKey("MeetingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.MeetingStatus", "MeetingStaus")
                        .WithMany()
                        .HasForeignKey("MeetingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoseMeeting");

                    b.Navigation("ClerkMeeting");

                    b.Navigation("MeetingPlace");

                    b.Navigation("MeetingStaus");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Vam", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", "File")
                        .WithMany("Vam")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.VamCode", "VamCode")
                        .WithMany("Vams")
                        .HasForeignKey("VamCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("VamCode");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.WorkFlow", b =>
                {
                    b.HasOne("VisitorManagment.DataLayer.Entities.VisitorManagment.ActionType", null)
                        .WithMany("WorkFlows")
                        .HasForeignKey("ActionTypeId");

                    b.HasOne("VisitorManagment.DataLayer.Entities.User.Role", "Role")
                        .WithMany("WorkFlows")
                        .HasForeignKey("RcvrRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Permissions.Permission", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.EshrafPeriodDef", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.Ranking.TblDepartmentType", b =>
                {
                    b.Navigation("TblDepartments");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.Role", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("WorkFlows");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.UserSub", b =>
                {
                    b.Navigation("Hameshes");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.User.Users", b =>
                {
                    b.Navigation("Hameshes");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.ActionType", b =>
                {
                    b.Navigation("Hameshes");

                    b.Navigation("WorkFlows");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.FileStatus", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Files", b =>
                {
                    b.Navigation("Cartables");

                    b.Navigation("FileAttachments");

                    b.Navigation("Hameshes");

                    b.Navigation("Vam");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Hamesh", b =>
                {
                    b.Navigation("Hameshes");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Meeting", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Personal", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.Priority", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.RequestSubject", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("VisitorManagment.DataLayer.Entities.VisitorManagment.VamCode", b =>
                {
                    b.Navigation("Hameshes");

                    b.Navigation("Vams");
                });
#pragma warning restore 612, 618
        }
    }
}
